apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python_app
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        app: python_app
    spec:
      containers:
      - name: apache2
        image: ar1609/$Image
        
    
