apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        app: apache
    spec:
      volumes:
      - name: html
        emptyDir: {}
      containers:
      - name: apache2
        image: ar1609/$Image
        
    
